version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  laravel_app:
    build: ./backend
    environment:
      - DB_HOST=mysql_db
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - mysql_db
    volumes:
      - ./backend:/var/www
      - ./.env:/var/www/.env
      - ./backend/storage/app:/var/www/storage/app
      - ./backend/storage/framework/cache:/var/www/storage/framework/cache
      - ./backend/storage/framework/sessions:/var/www/storage/framework/sessions
      - ./backend/storage/framework/views:/var/www/storage/framework/views
      - ./backend/storage/logs:/var/www/storage/logs
      - ./backend/bootstrap/cache:/var/www/bootstrap/cache

  nextjs_web:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - laravel_app

  nginx:
    build: ./nginx
    ports:
      - "8000:80"
    depends_on:
      - laravel_app

  # 💡 SERVICIO phpMYADMIN AÑADIDO
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      # Pone el host de la base de datos (nombre del servicio)
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "8080:80" # Puedes acceder a phpMyAdmin en http://localhost:8080
    depends_on:
      - mysql_db
    restart: always # Asegura que se reinicie si falla
    
volumes:
  mysql_data: